Week 3 Assignments
pesto-students/p7-vignesh-shubhamkar-suryawanshi pull request #5
Opened 2022-11-24 12:52 UTC by shubhamkar-suryawanshi

2022-11-24 14:57 UTC, shubhamkar-suryawanshi commented
@veer-auro 

This one is week 3 assignment. Please Review

2022-11-30 09:44 UTC, veer-auro requested changes

2022-11-30 09:44 UTC, veer-auro commented on Week-3/Assignment1.js
> +  return a + b;
should work with multiple arguments slowFun(1,2,3)

2022-11-30 09:44 UTC, veer-auro commented on Week-3/Assignment2.js
> +var person = {
Why redeclare var

2022-11-30 09:44 UTC, veer-auro commented on Week-3/Assignment2.js
> +foo.call(person, ["Hello"]);
Since when does call accept arrays ?

2022-11-30 09:44 UTC, veer-auro commented on Week-3/Assignment3.js
> +log(); // output will be 0 as we are typing message before increment happend
Need an explanation on why this program works the way it does. And how can you fix this.

2022-11-30 09:44 UTC, veer-auro commented on Week-3/Assignment4.js
> +const stackAns = createStack();
Suggest you to Object freeze the item returned

2022-11-30 09:44 UTC, veer-auro commented on Week-3/Assignment1.js
> +  return a + b;
Also doesn not work with single parameter slowFun(2)

2022-12-06 04:36 UTC, shubhamkar-suryawanshi commented on Week-3/Assignment2.js
> +var person = {
It was mistake

2022-12-06 06:14 UTC, shubhamkar-suryawanshi commented on Week-3/Assignment2.js
> +foo.call(person, ["Hello"]);
It was mistake...
I'm thinking like, still how it show the correct answer

2022-12-06 06:39 UTC, shubhamkar-suryawanshi commented on Week-3/Assignment3.js
> +log(); // output will be 0 as we are typing message before increment happend
When we print the message, that time count was 0 and we are not updating the message when count is updating --> simply message is created only once and count is incrementing
and we can solve it by two ways
1. instead of printing message, print the count
2. Printing message along with increment

both methods are added in code as a comment

2022-12-06 12:45 UTC, shubhamkar-suryawanshi commented on Week-3/Assignment4.js
> +const stackAns = createStack();
Here the question was :
The stack works as expected, but with one small problem. Anyone can modify items array directly because stack.items property is exposed.
That's an issue since it breaks the encapsulation of the stack: only push() and pop() methods should be public, but stack.items or any other details shouldn't be accessible.
Refactor the above stack implementation, using the concept of closure, such that there is no way to access items array outside of createStack() function scope:

2022-12-09 13:47 UTC, shubhamkar-suryawanshi commented on Week-3/Assignment4.js
> +const stackAns = createStack();
done

2022-12-18 17:03 UTC, veer-auro approved these changes
LGTM

2022-12-18 17:03 UTC, merged