Week-4 Assignments
pesto-students/p7-vignesh-shubhamkar-suryawanshi pull request #6
Opened 2022-12-11 11:41 UTC by shubhamkar-suryawanshi

@veer-auro Please review the assignments of Week 4

2022-12-15 20:48 UTC, veer-auro requested changes

2022-12-15 20:48 UTC, veer-auro commented on Week-4/assignment3.js
> +console.log([...Fibonacci(8)]);
1. Should display list of fibonacci numbers. 
2. Should start with 0

2022-12-15 20:48 UTC, veer-auro commented on Week-4/assignment2.js
> +class Person {
Don't use class here. Use prototype object to implement inheritance.

2022-12-19 11:24 UTC, shubhamkar-suryawanshi commented
@veer-auro pls review

2023-01-19 17:03 UTC, veer-auro approved these changes

2023-01-19 17:03 UTC, merged