week-5 assignment
pesto-students/p7-vignesh-shubhamkar-suryawanshi pull request #7
Opened 2022-12-19 15:25 UTC by shubhamkar-suryawanshi

@veer-auro Please Review

2023-01-19 17:42 UTC, veer-auro commented
@shubhamkar-suryawanshi Wheres the question 4 of assignment

2023-01-19 17:56 UTC, veer-auro requested changes

2023-01-19 17:56 UTC, veer-auro commented on Week-5/assignment1.js
> +function* simpleGenerator() {
you need to call doTask1, doTask2, doTask3 using generator

2023-01-19 17:56 UTC, veer-auro commented on Week-5/assignment1.js
> +    console.log(`${showOrderDetails}`);
Maybe randomly resolve reject here just to demonstrate all 3 states of promise

2023-01-30 14:58 UTC, veer-auro commented
@shubhamkar-suryawanshi Left some comments. Please resolve

2023-01-31 16:03 UTC, shubhamkar-suryawanshi commented
ok sir

2023-02-10 07:17 UTC, merged